### ISSUE TITLE
How i can delete a specific line

### ISSUE THREAD

**Issue by Timbuktu1982** [ionic-team/trapeze#158]
Hi there,

how i can delete a specific line, e.g.:
`<meta-data android:name="com.google.firebase.messaging.default_notification_icon" android:resource="@drawable-anydpi-v24/push_icon_new_message" />`

Following code is not working:
```
- file: AndroidManifest.xml
              delete: <meta-data android:name="com.google.firebase.messaging.default_notification_icon" android:resource="@drawable-anydpi-v24/push_icon_new_message" />
```

Following code is not usable, because its delete all <meta-data />-lines:
```
- file: AndroidManifest.xml
              delete: //meta-data
```

How i can do this correctly?

**Comment by mlynch** [comment]
Can you try a more specific XPath selector, like `//meta-data[@android:name='com.google.firebase.messaging.default_notification_icon']

**Comment by Timbuktu1982** [comment]
Hi Max,
thank you for your response.
Unfortunately it does not work.

 ```
- file: AndroidManifest.xml
              delete: //meta-data[@android:name='com.google.firebase.messaging.default_notification_icon']>
```
causes
```
Error: XPath parse error
    at XPathParser.parse (/var/www/apps/projects/stoma-navi/node_modules/xpath/xpath.js:1278:27)
    at new XPathExpression (/var/www/apps/projects/stoma-navi/node_modules/xpath/xpath.js:4341:24)
    at exports.selectWithResolver (/var/www/apps/projects/stoma-navi/node_modules/xpath/xpath.js:4818:26)
    at XmlFile.select (/var/www/apps/projects/stoma-navi/node_modules/xpath/xpath.js:4813:28)
    at XmlFile.deleteNodes (/var/www/apps/projects/stoma-navi/node_modules/@trapezedev/configure/node_modules/@trapezedev/project/dist/xml.js:88:82)
    at execute (/var/www/apps/projects/stoma-navi/node_modules/@trapezedev/configure/dist/operations/android/manifest.js:18:101)
    at runOperation (/var/www/apps/projects/stoma-navi/node_modules/@trapezedev/configure/dist/operations/index.js:67:16)
    at executeOperations (/var/www/apps/projects/stoma-navi/node_modules/@trapezedev/configure/dist/tasks/run.js:52:41)
    at async runCommand (/var/www/apps/projects/stoma-navi/node_modules/@trapezedev/configure/dist/tasks/run.js:31:9)
    at async /var/www/apps/projects/stoma-navi/node_modules/@trapezedev/configure/dist/index.js:56:13
```

**Comment by mlynch** [comment]
This will work, just need to fix your xpath. Try removing the `>` character. https://devhints.io/xpath

**Comment by Timbuktu1982** [comment]
Oh sorry, thank you so much. It work's fine...

**Comment by Timbuktu1982** [comment]
Can you add this to documentation, so other user can see this case to delete a specific line/tag?
