### ISSUE TITLE
Error: EISDIR: illegal operation on a directory

### ISSUE THREAD

**Issue by paulociva** [ionic-team/trapeze#98]
I am trying to use trapeze inside a nx monorepo, but I am getting the following error when I enable the ios settings and run await project.load();
`Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (node:fs:727:3)
    at tryReadSync (node:fs:433:20)
    at Object.readFileSync (node:fs:479:19)
    at pbxProject.parseSync (C:\Users\paulo\projetos\github\trapeze\node_modules\xcode\lib\pbxProject.js:61:28)
    at parsePbxProject (C:\Users\paulo\projetos\github\trapeze\node_modules\@trapezedev\project\src\util\pbx.ts:10:15)
    at async IosProject.pbx (C:\Users\paulo\projetos\github\trapeze\node_modules\@trapezedev\project\src\ios\project.ts:606:23)    
    at async IosProject.load (C:\Users\paulo\projetos\github\trapeze\node_modules\@trapezedev\project\src\ios\project.ts:44:18)    
    at async MobileProject.load (C:\Users\paulo\projetos\github\trapeze\node_modules\@trapezedev\project\src\project.ts:73:5)      
    at async run (C:\Users\paulo\projetos\github\trapeze\test-trapeze.ts:16:3) {
  errno: -4068,
  syscall: 'read',
  code: 'EISDIR'
}`

As I couldn't identify if it is something due to the folder structure, or something I am doing wrong, I created a repository to simulate the error: https://github.com/paulociva/test-trapeze

**Comment by jonz94** [comment]
Hi @paulociva 

I also get same error today when trying trapeze's project API.

After some try and error, I figure out that the path for **Capacitor iOS** should be set to `ios/App` instead of `ios` (https://trapeze.dev/docs/Frameworks/capacitor#api)

So change the [test-trapeze.ts file](https://github.com/paulociva/test-trapeze/blob/447e084c35a462b341ad4afa569eb09cde18e4b7/test-trapeze.ts) as following should resolve this issue:

```diff
import { MobileProject, MobileProjectConfig } from '@trapezedev/project';

const config: MobileProjectConfig = {
  ios: {
-    path: 'ios',
+    path: 'ios/App',
  },
  android: {
    path: 'android',
  },
};

async function run() {
  const project = new MobileProject('apps/test', config);
  await project.load();

  await project.commit();
}

run().then();
```

**Comment by paulociva** [comment]
Hey @jonz94, yes, changing the path as you said, the script works again, thank you.
